spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: api
              uri:
                lb://api
              predicates:
                - Path=/api/**
            - id: replay
              uri:
                lb://replay
              predicates:
                - Path=/replay/**
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE
  application:
    name: gateway


