spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dota?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #jackson:
   # serialization:
    #  fail-on-empty-beans: false
